### ISSUE TITLE
cedet git submodule seems to be dead

### ISSUE THREAD

**Issue by kurtjx** [EnigmaCurry/emacs#1]
$git submodule update

fails with other end hung up unexpected

**Comment by kurtjx** [comment]
Initialized empty Git repository in /home/kurtjx/.emacs.d/vendor/jde/.git/
fatal: The remote end hung up unexpectedly
Clone of 'git://git.hcoop.net/git/mwolson/debian/jde.git' into submodule path 'vendor/jde' failed

seems to effect the jde submodule too

**Comment by tianyi1111** [comment]
remove .emacs.d, reclone reop, then
edit .gitmodule
replace "url" in "[submodule "vendor/cedet"]" to "git://github.com/emacsmirror/cedet.git"
you can find all emacs script mirror in "https://github.com/emacsmirror"

**Comment by nagyv** [comment]
I've tried the above, but git submodule update still fails with cedet:

fatal: reference is not a tree: 8170082e7c0a167641b95b75353db0a373712a5d
Unable to checkout '8170082e7c0a167641b95b75353db0a373712a5d' in submodule path 'vendor/cedet'
